version: '3.3'

services:
  app:
    env_file: ".env"
    build:
      context: services/app
      dockerfile: Dockerfile.development
    command: sh -c "rm -f tmp/pids/server.pid && bundle exec bin/rails s -b '0.0.0.0' -p 3000"
    volumes:
      - "~/.bash_history:/.bash_history"
      - "./services/app:/usr/src/app:cached"
      - "/tmp:/tmp:delegated"
    depends_on:
      - db
  nginx:
    build:
      context: services/nginx
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - "./services/nginx/domain.conf:/etc/nginx/conf.d/default.conf"
    depends_on:
      - app
  db:
    image: postgres:10.3-alpine
