version: '3.3'

services:
  app:
    build:
      context: services/app
      dockerfile: Dockerfile.development
    command: sh -c "rm -f tmp/pids/server.pid && bundle exec bin/rails s -b '0.0.0.0' -p 3000"
    volumes:
      - "~/.bash_history:/.bash_history"
      - "./services/app:/usr/src/app:cached"
      - "/tmp:/tmp:delegated"
  nginx:
    build:
      context: services/nginx
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - app
